# ABOUTME: Jupyter notebook export tools.
# Generates .ipynb notebooks from conversations, process graphs, and visualizations.

"""
Notebook Export Tools for OpenEO AI.

Provides:
- NotebookGenerator for creating Jupyter notebooks
- Conversion of conversations to reproducible notebooks
- Process graph documentation
- Quality metrics cells
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class NotebookCell:
    """A single notebook cell."""
    cell_type: str  # "code" or "markdown"
    source: List[str]
    metadata: Dict[str, Any] = field(default_factory=dict)
    outputs: List[Dict[str, Any]] = field(default_factory=list)
    execution_count: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to nbformat cell dictionary."""
        cell = {
            "cell_type": self.cell_type,
            "metadata": self.metadata,
            "source": self.source,
        }

        if self.cell_type == "code":
            cell["outputs"] = self.outputs
            cell["execution_count"] = self.execution_count

        return cell


class NotebookGenerator:
    """
    Generate Jupyter notebooks from OpenEO AI conversations.

    Usage:
        generator = NotebookGenerator()
        generator.add_markdown("# Analysis Report")
        generator.add_code("import openeo\\nconn = openeo.connect(...)")
        generator.add_process_graph(graph_dict)

        notebook_dict = generator.to_notebook()
        generator.save("analysis.ipynb")
    """

    NBFORMAT_VERSION = 4
    NBFORMAT_MINOR = 5

    def __init__(self, title: str = "OpenEO AI Analysis"):
        """Initialize the generator."""
        self.title = title
        self.cells: List[NotebookCell] = []
        self._add_header()

    def _add_header(self):
        """Add notebook header cell."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        header = f"""# {self.title}

**Generated by OpenEO AI Assistant**

Date: {timestamp}

---

This notebook contains reproducible Earth Observation analysis code generated from a conversational AI session."""

        self.add_markdown(header)

    def add_markdown(self, content: str) -> None:
        """Add a markdown cell."""
        # Split content into lines for nbformat
        lines = [line + "\n" for line in content.split("\n")]
        if lines:
            lines[-1] = lines[-1].rstrip("\n")  # Remove trailing newline from last line

        self.cells.append(NotebookCell(
            cell_type="markdown",
            source=lines,
        ))

    def add_code(self, code: str, outputs: List[Dict] = None) -> None:
        """Add a code cell."""
        lines = [line + "\n" for line in code.split("\n")]
        if lines:
            lines[-1] = lines[-1].rstrip("\n")

        self.cells.append(NotebookCell(
            cell_type="code",
            source=lines,
            outputs=outputs or [],
        ))

    def add_setup_cell(
        self,
        openeo_url: str = "https://earthengine.openeo.org",
        include_auth: bool = True
    ) -> None:
        """Add OpenEO setup/connection cell."""
        self.add_markdown("## Setup\n\nConnect to the OpenEO backend and authenticate.")

        code = f'''import openeo
import json
import matplotlib.pyplot as plt
import numpy as np

# Connect to OpenEO backend
connection = openeo.connect("{openeo_url}")'''

        if include_auth:
            code += """

# Authenticate (uncomment one method)
# connection.authenticate_basic("username", "password")
# connection.authenticate_oidc()
print(f"Connected to: {connection.capabilities().title()}")"""

        self.add_code(code)

    def add_process_graph(
        self,
        process_graph: Dict[str, Any],
        title: str = "Process Graph",
        execute: bool = True
    ) -> None:
        """Add a process graph cell."""
        self.add_markdown(f"## {title}\n\nThe following process graph defines the analysis workflow.")

        # Format process graph as code
        graph_str = json.dumps(process_graph, indent=2)

        code = f'''# Process Graph
process_graph = {graph_str}

# Display graph structure
print(json.dumps(process_graph, indent=2))'''

        self.add_code(code)

        if execute:
            execution_code = '''# Create and execute datacube
datacube = connection.load_collection(
    process_graph["load1"]["arguments"]["id"],
    spatial_extent=process_graph["load1"]["arguments"].get("spatial_extent"),
    temporal_extent=process_graph["load1"]["arguments"].get("temporal_extent"),
    bands=process_graph["load1"]["arguments"].get("bands")
)

# Execute synchronously (for small areas) or as batch job
result = datacube.execute()
print(f"Result shape: {result.shape if hasattr(result, 'shape') else 'N/A'}")'''

            self.add_code(execution_code)

    def add_quality_metrics(self, metrics: Dict[str, Any]) -> None:
        """Add quality metrics cell."""
        self.add_markdown("## Data Quality Metrics\n\nAssessment of the retrieved data quality.")

        metrics_str = json.dumps(metrics, indent=2)

        code = f'''# Quality Metrics
quality_metrics = {metrics_str}

# Display quality assessment
print("Quality Grade:", quality_metrics.get("grade", "N/A"))
print("Completeness:", quality_metrics.get("completeness_pct", "N/A"), "%")
print("CV:", quality_metrics.get("cv_pct", "N/A"), "%")

if "recommendation" in quality_metrics:
    print("\\nRecommendation:", quality_metrics["recommendation"])'''

        self.add_code(code)

    def add_visualization(
        self,
        viz_type: str,
        data: Dict[str, Any],
        title: str = "Visualization"
    ) -> None:
        """Add visualization cell."""
        self.add_markdown(f"## {title}")

        if viz_type == "map":
            code = '''# Map Visualization
import folium

# Create map centered on extent
center_lat = (extent["south"] + extent["north"]) / 2
center_lon = (extent["west"] + extent["east"]) / 2

m = folium.Map(location=[center_lat, center_lon], zoom_start=10)

# Add raster overlay (if available)
# folium.raster_layers.ImageOverlay(
#     image=result_path,
#     bounds=[[extent["south"], extent["west"]], [extent["north"], extent["east"]]],
#     opacity=0.7
# ).add_to(m)

m'''

        elif viz_type == "chart":
            chart_data = data.get("series", [])
            labels = data.get("labels", [])

            code = f'''# Chart Visualization
import matplotlib.pyplot as plt

labels = {json.dumps(labels)}
'''
            for i, series in enumerate(chart_data[:3]):  # Limit to 3 series
                code += f'''
series_{i} = {json.dumps(series.get("values", []))}
plt.plot(labels, series_{i}, label="{series.get("name", f"Series {i}")}")'''

            code += '''

plt.xlabel("''' + data.get("xLabel", "X") + '''")
plt.ylabel("''' + data.get("yLabel", "Y") + '''")
plt.title("''' + data.get("title", title) + '''")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()'''

        else:
            code = f'''# Visualization data
viz_data = {json.dumps(data, indent=2)}
print(json.dumps(viz_data, indent=2))'''

        self.add_code(code)

    def add_conversation_log(self, messages: List[Dict[str, Any]]) -> None:
        """Add conversation log as markdown."""
        self.add_markdown("## Conversation Log\n\nSummary of the AI conversation that generated this analysis.")

        log_lines = []
        for msg in messages[-20:]:  # Limit to last 20 messages
            role = msg.get("role", "unknown").title()
            content = msg.get("content", "")

            if isinstance(content, str):
                # Truncate long messages
                if len(content) > 500:
                    content = content[:500] + "..."
                log_lines.append(f"**{role}:** {content}")
            else:
                log_lines.append(f"**{role}:** [Complex content]")

        self.add_markdown("\n\n".join(log_lines))

    def add_custom_section(self, title: str, markdown: str, code: str = None) -> None:
        """Add a custom section with markdown and optional code."""
        self.add_markdown(f"## {title}\n\n{markdown}")
        if code:
            self.add_code(code)

    def to_notebook(self) -> Dict[str, Any]:
        """Convert to notebook dictionary (nbformat 4)."""
        return {
            "nbformat": self.NBFORMAT_VERSION,
            "nbformat_minor": self.NBFORMAT_MINOR,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "name": "python",
                    "version": "3.11"
                },
                "openeo_ai": {
                    "generated": datetime.now().isoformat(),
                    "title": self.title,
                }
            },
            "cells": [cell.to_dict() for cell in self.cells]
        }

    def to_json(self, indent: int = 1) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_notebook(), indent=indent)

    def save(self, path: str) -> str:
        """
        Save notebook to file.

        Args:
            path: Output file path (.ipynb)

        Returns:
            Path to saved file
        """
        if not path.endswith(".ipynb"):
            path += ".ipynb"

        with open(path, "w", encoding="utf-8") as f:
            f.write(self.to_json())

        logger.info(f"Saved notebook to: {path}")
        return path


async def export_notebook_tool(args: Dict[str, Any]) -> Dict[str, Any]:
    """
    Export conversation and results to Jupyter notebook.

    Args:
        args: {
            "title": "Notebook title",
            "messages": [...],  # Conversation messages
            "process_graph": {...},  # Process graph
            "visualizations": [...],  # Visualizations
            "quality_metrics": {...},  # Quality metrics
            "output_path": "analysis.ipynb"
        }

    Returns:
        Path to generated notebook
    """
    title = args.get("title", "OpenEO AI Analysis")
    messages = args.get("messages", [])
    process_graph = args.get("process_graph")
    visualizations = args.get("visualizations", [])
    quality_metrics = args.get("quality_metrics")
    output_path = args.get("output_path", "/tmp/openeo_analysis.ipynb")

    try:
        generator = NotebookGenerator(title=title)

        # Add setup cell
        generator.add_setup_cell()

        # Add process graph if provided
        if process_graph:
            generator.add_process_graph(process_graph)

        # Add quality metrics if provided
        if quality_metrics:
            generator.add_quality_metrics(quality_metrics)

        # Add visualizations
        for i, viz in enumerate(visualizations[:5]):  # Limit to 5
            generator.add_visualization(
                viz_type=viz.get("type", "chart"),
                data=viz.get("data", {}),
                title=viz.get("title", f"Visualization {i + 1}")
            )

        # Add conversation log
        if messages:
            generator.add_conversation_log(messages)

        # Add conclusion
        generator.add_markdown("""## Next Steps

1. Run all cells to reproduce the analysis
2. Modify parameters as needed
3. Add additional processing steps

---
*Generated by OpenEO AI Assistant*""")

        # Save notebook
        saved_path = generator.save(output_path)

        return {
            "content": [{
                "type": "text",
                "text": json.dumps({
                    "success": True,
                    "path": saved_path,
                    "cells": len(generator.cells),
                    "message": f"Notebook saved to {saved_path}"
                })
            }]
        }

    except Exception as e:
        logger.error(f"Notebook export error: {e}")
        return {
            "content": [{
                "type": "text",
                "text": json.dumps({
                    "success": False,
                    "error": str(e)
                })
            }]
        }


def create_notebook_tools(config=None) -> Dict[str, Any]:
    """Create notebook export tools."""
    return {
        "export_notebook": export_notebook_tool,
    }


# Tool definition for Claude API
NOTEBOOK_TOOL_DEFINITIONS = [
    {
        "name": "export_notebook",
        "description": "Export the current conversation and results to a Jupyter notebook (.ipynb) for reproducibility.",
        "input_schema": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Title for the notebook"
                },
                "process_graph": {
                    "type": "object",
                    "description": "Process graph to include"
                },
                "output_path": {
                    "type": "string",
                    "description": "Output file path (default: /tmp/openeo_analysis.ipynb)"
                }
            },
            "required": []
        }
    }
]
