"""create_tables

Revision ID: 9ad7e6b87a94
Revises: 
Create Date: 2026-02-05 10:21:12.707278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ad7e6b87a94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('process', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'queued', 'running', 'canceled', 'finished', 'error', name='status'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('synchronous', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('udps',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('process_graph', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('returns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oidc_sub', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('oidc_sub'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('udps')
    op.drop_table('jobs')
    # ### end Alembic commands ###
