# ABOUTME: Utility modules for OpenEO AI Assistant.
# Contains geocoding, temporal parsing, retry logic, error handling, and other helper functions.

from .geocoding import resolve_location, LocationResult
from .temporal import parse_temporal_expression, TemporalResult
from .error_handler import (
    ErrorHandler,
    ErrorType,
    Severity,
    HandledError,
    ErrorContext,
    RecoverySuggestion,
    get_error_handler,
    handle_error,
    check_oversight,
)
from .retry import (
    RetryConfig,
    RetryResult,
    CircuitBreaker,
    retry_async,
    with_retry,
    ErrorRecoveryStrategy,
    get_circuit_breaker,
)
from .extent_validator import (
    ExtentValidator,
    ExtentEstimate,
    estimate_extent_size,
    validate_extent,
)
from .geospatial import (
    GeospatialValidator,
    ValidationResult,
    validate_extent as validate_geospatial_extent,
    validate_crs,
    split_antimeridian,
    get_utm_zone_for_extent,
    SUPPORTED_CRS,
)
from .quality_metrics import (
    QualityMetricsCalculator,
    CloudCoverageEstimate,
    TemporalCoverageEstimate,
    DataQualityMetrics,
    estimate_cloud_coverage,
    estimate_temporal_coverage,
    get_quality_metrics,
)
from .schema_validator import (
    SchemaValidator,
    SchemaValidationResult,
    SchemaValidationError,
    get_schema_validator,
    validate_tool_input,
    validate_process_graph,
    deep_validate_graph,
)

__all__ = [
    "resolve_location",
    "LocationResult",
    "parse_temporal_expression",
    "TemporalResult",
    "ErrorHandler",
    "ErrorType",
    "Severity",
    "HandledError",
    "ErrorContext",
    "RecoverySuggestion",
    "get_error_handler",
    "handle_error",
    "check_oversight",
    "RetryConfig",
    "RetryResult",
    "CircuitBreaker",
    "retry_async",
    "with_retry",
    "ErrorRecoveryStrategy",
    "get_circuit_breaker",
    "ExtentValidator",
    "ExtentEstimate",
    "estimate_extent_size",
    "validate_extent",
    "GeospatialValidator",
    "ValidationResult",
    "validate_geospatial_extent",
    "validate_crs",
    "split_antimeridian",
    "get_utm_zone_for_extent",
    "SUPPORTED_CRS",
    "QualityMetricsCalculator",
    "CloudCoverageEstimate",
    "TemporalCoverageEstimate",
    "DataQualityMetrics",
    "estimate_cloud_coverage",
    "estimate_temporal_coverage",
    "get_quality_metrics",
    "SchemaValidator",
    "SchemaValidationResult",
    "SchemaValidationError",
    "get_schema_validator",
    "validate_tool_input",
    "validate_process_graph",
    "deep_validate_graph",
]
